### ISSUE TITLE
Current build (after pro search) is broken

### ISSUE THREAD

**Issue by arsaboo** [rashadphz/farfalle#64]
I am seeing with the latest build:

![image](https://github.com/rashadphz/farfalle/assets/18319734/2fb8ba09-e490-45e8-9c7f-ff0426fe151d)

Errors in browser console:

![image](https://github.com/rashadphz/farfalle/assets/18319734/f75715ad-e391-4637-a7ef-5d0b3788a8ff)

**Comment by rashadphz** [comment]
Shoot, thanks for catching this, I’ll fix it

**Comment by rashadphz** [comment]
Should be fixed, feel free to re-open if you run into any more issues.

**Comment by arsaboo** [comment]
@rashadphz The UI now shows, and the query starts, but I am not seeing any output. I see the following in the browser console:

![image](https://github.com/rashadphz/farfalle/assets/18319734/11ea03ed-f85f-417e-a75f-ae3a292b810c)

I am guessing it is one of the changed ports that is causing the issue. Can you please double check my configs?

compose file:
```yaml
services:
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    restart: always
    ports:
      - "8003:8000"
    environment:
      - SEARCH_PROVIDER=${SEARCH_PROVIDER:-searxng}
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL:-http://searxng:8080}

      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - BING_API_KEY=${BING_API_KEY}

      - OLLAMA_API_BASE=${OLLAMA_API_BASE:-http://host.docker.internal:11434}

      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}

      - AZURE_DEPLOYMENT_NAME=${AZURE_DEPLOYMENT_NAME}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_API_BASE=${AZURE_API_BASE}
      - AZURE_API_VERSION=${AZURE_API_VERSION}

      - OPENAI_MODE=${OPENAI_MODE}

      - CUSTOM_MODEL=${CUSTOM_MODEL}

      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg2://postgres:password@db:5432/postgres}
      - DB_ENABLED=${DB_ENABLED:-True}

      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-False}
      - REDIS_URL=${REDIS_URL}

      - ENABLE_LOCAL_MODELS=${ENABLE_LOCAL_MODELS:-True}

    entrypoint: >
      /bin/sh -c "
        cd /workspace/src/backend &&
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "
    develop:
      watch:
        - action: sync
          path: ./src/backend
          target: /workspace/src/backend
    networks:
      - farfalle-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
        - NEXT_PUBLIC_LOCAL_MODE_ENABLED=${NEXT_PUBLIC_LOCAL_MODE_ENABLED:-true}
        - NEXT_PUBLIC_PRO_MODE_ENABLED=${NEXT_PUBLIC_PRO_MODE_ENABLED:-true}
    restart: always
    ports:
      - "3013:3000"
    develop:
      watch:
        - action: sync
          path: ./src/frontend
          target: /app
          ignore:
            - node_modules/
    networks:
      - farfalle-network
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - "5435:5432"
    volumes:
      - /Users/asaboo/Documents/Containers/farfalle:/var/lib/postgresql/data
    networks:
      - farfalle-network

networks:
  farfalle-network:
    name: farfalle-network
```

.env
```yaml
SEARCH_PROVIDER=searxng
SEARXNG_BASE_URL=http://host.docker.internal:4002/
OPENAI_API_KEY=REDACTED
TAVILY_API_KEY=REDACTED
ENABLE_LOCAL_MODELS=True
NEXT_PUBLIC_LOCAL_MODE_ENABLED=True
NEXT_PUBLIC_PRO_MODE_ENABLED=True
OLLAMA_HOST=http://host.docker.internal:11434
GROQ_API_KEY=REDACTED
OLLAMA_API_BASE=http://host.docker.internal:11434

DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/postgres
DB_ENABLED=True
```
