### ISSUE TITLE
Option to use OpenRouter Models

### ISSUE THREAD

**Issue by PierrunoYT** [rashadphz/farfalle#80]
Option to use OpenRouter Models

**Comment by bpawnzZ** [comment]
Did you ever figure this out?? I just found this project and it's unclear if we can see a base URL. If so openrouter can handle

**Comment by bpawnzZ** [comment]
PS.. Its easy to get this going with Openrouter running a proxy on LiteLLM.  

#create a config.toml for models with generic openai format for LiteLLM and run a  litellm proxy in a container with taht config and good to
````
model_list:
  - model_name: meta-llama/llama-3-70b-instruct:nitro
    litellm_params:
      model: openai/meta-llama/llama-3-70b-instruct:nitro
      api_base: https://openrouter.ai/api/v1
      api_key: 
  - model_name: anthropic/claude-3.5-sonnet
    litellm_params:
      model: openai/anthropic/claude-3.5-sonnet       
      api_base: https://openrouter.ai/api/v1                  
      api_key: 

````
